# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/bram_sin_cos/bram_sin_cos.xci
# IP: The module: 'bram_sin_cos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/bram_sin_cos/bram_sin_cos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_sin_cos'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/bram_sin_cos/bram_sin_cos.xci
# IP: The module: 'bram_sin_cos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/bram_sin_cos/bram_sin_cos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_sin_cos'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
