# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/plot_bram/plot_bram.xci
# IP: The module: 'plot_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/plot_bram/plot_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'plot_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/plot_bram/plot_bram.xci
# IP: The module: 'plot_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/plot_bram/plot_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'plot_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
