# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/ppi_bg/ppi_bg.xci
# IP: The module: 'ppi_bg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/ppi_bg/ppi_bg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ppi_bg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/ppi_bg/ppi_bg.xci
# IP: The module: 'ppi_bg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/ipcores/ppi_bg/ppi_bg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ppi_bg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
