# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/xuyi/Desktop/FPGA display/08_4_hdmi_loop/ipcores/bram_display_b/bram_display_b.xci
# IP: The module: 'bram_display_b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xuyi/Desktop/FPGA display/08_4_hdmi_loop/ipcores/bram_display_b/bram_display_b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_display_b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/xuyi/Desktop/FPGA display/08_4_hdmi_loop/ipcores/bram_display_b/bram_display_b.xci
# IP: The module: 'bram_display_b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xuyi/Desktop/FPGA display/08_4_hdmi_loop/ipcores/bram_display_b/bram_display_b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_display_b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
