# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/bram_display_a_2/bram_display_a.xci
# IP: The module: 'bram_display_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/bram_display_a_2/bram_display_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_display_a'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/bram_display_a_2/bram_display_a.xci
# IP: The module: 'bram_display_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/bram_display_a_2/bram_display_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_display_a'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
