# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA_HDMI/08_4_hdmi_loop/hdmi_loop.srcs/sources_1/ip/sys_pll_1/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
