# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/rom_char/rom_char.xci
# IP: The module: 'rom_char' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/rom_char/rom_char_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_char'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/rom_char/rom_char.xci
# IP: The module: 'rom_char' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yi/Desktop/FPGA/08_4_hdmi_loop/ipcores/rom_char/rom_char_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_char'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
